kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: access-service-via-apiserver
rules:
- apiGroups: [""]
  resources: ["services", "services/proxy"]
  verbs: ["get", "list", "create", "update"]
